import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json();

  return {
    props: {
      users: data,
    },
  };
};

const UsersList = ({ users }) => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>First App || Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-20 flex items-center">
        <div className="container mx-auto">
          <h2 className="text-center text-5xl font-bold mb-8">User Lists</h2>
          <div>
            {users.length > 0 && (
              <ul>
                {users.map((user) => (
                  <li key={user.id} className="block  mb-4">
                    <Link href={`/users/${user.id}`}>
                      <a className="bg-white text-black p-4 font-bold text-xl transition duration-300 hover:text-red-700 border-l-4 border-red-600 inline-block w-96">
                        {user.name}
                      </a>
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default UsersList;
